name: Secret Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  repository-secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Repository Secret
        run: |
          if [ -z "${{ secrets.REPOSITORY_SECRET }}" ]; then
            echo "Repository secret is not set"
            exit 1
          else
            echo "Repository secret is set"
          fi
